### PR TITLE
feat(TrafficControl): Add traffic control button

### PR DESCRIPTION
**Pull request by device25**
A Traffic Control add control to toggle traffic on map.

### CODE REVIEW

**Comment by anatolysukhanov** [comment]
When do you expect this could be finished?

**Comment by device25** [comment]
@anatolysukhanov I’m a little busy at the moment, but I’ll try to finish this week or maybe next

**Comment by device25** [comment]
@stepankuzmin could you check component API, what do you think?

**Comment by anatolysukhanov** [comment]
> @anatolysukhanov I’m a little busy at the moment, but I’ll try to finish this week or maybe next

Thank you, I appreciate your efforts.

**Comment by stepankuzmin** [comment]
👏

**Pull request merged**
